---
abstract: 'Avro message producer for Apache Kafka.'
author:
  - 'Alvaro Livraghi'
build_requires:
  ExtUtils::MakeMaker: '0'
  Math::BigInt: '1.89'
  Test::Exception: '0.43'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Kafka-Producer-Avro
no_index:
  directory:
    - t
    - inc
    - t
    - inc
requires:
  Avro::BinaryEncoder: '0'
  Avro::Schema: '0'
  Confluent::SchemaRegistry: '0.03'
  JSON::XS: '3.02'
  Kafka::Producer: '1.07'
  perl: '5.010'
resources:
  bugtracker: https://github.com/alivraghi/Kafka-Producer-Avro/issues
  homepage: https://github.com/alivraghi/Kafka-Producer-Avro
  repository: https://github.com/alivraghi/Kafka-Producer-Avro.git
version: '0.01'
