---
abstract: 'Avro message producer for Apache Kafka.'
author:
  - 'Alvaro Livraghi'
build_requires:
  ExtUtils::MakeMaker: '0'
  Math::BigInt: '1.89'
  Test::Exception: '0.43'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Kafka-Producer-Avro
no_index:
  directory:
    - t
    - inc
    - t
    - inc
requires:
  Avro::BinaryEncoder: v1.10.1
  Avro::Schema: v1.10.1
  Confluent::SchemaRegistry: '0.010000'
  JSON::XS: v4.30.0
  Kafka::Producer: v1.8.0
  perl: '5.010'
resources:
  bugtracker: https://github.com/alivraghi/Kafka-Producer-Avro/issues
  homepage: https://github.com/alivraghi/Kafka-Producer-Avro
  repository: https://github.com/alivraghi/Kafka-Producer-Avro.git
version: v1.0.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
